algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
var
   nu: real



inicio

   escreva ("escreva um número para saber se ele é negativo ou positivo: ")
   leia (nu)

   se (nu<0) entao
      escreva ("seu número é negativo")
   senao
      se (nu=0) entao
         escreval("Seu número é nulo.")
      senao
         escreva ("seu número é positivo")
      fimse
   fimse



fimalgoritmo